Matrix Generator
alexander-kurdakov/Programming_Course_SPbU pull request #10
Opened 2021-05-05 15:29 UTC by alexander-kurdakov

Matrix Generator
use --help to get information about available arguments

2021-05-05 16:59 UTC, gsvgit requested changes
Меня терзают смутные сомнения. Где-то я такой генератор уже видел.

2021-05-05 16:59 UTC, gsvgit commented on src/MatrixGenerator/Main.fs
> +            | Sparsity _ -> "Specify the sparsity as number from 0.0 to 1.0"
Может стоит явно написать, что оно означает?

2021-05-05 16:59 UTC, gsvgit commented on src/eighthHomework/QuadTree.fs
> +    static member transitiveClosure (exTree: extendedTree<'t>) (algStruct: AlgebraicStruct<'t>) =
И всё же. Почекму он static?

2021-05-05 17:59 UTC, alexander-kurdakov commented
> Меня терзают смутные сомнения. Где-то я такой генератор уже видел.

Да, я смотрел решение Ивана.

2021-05-05 18:11 UTC, gsvgit commented
> > Меня терзают смутные сомнения. Где-то я такой генератор уже видел.
> 
> Да, я смотрел решение Ивана.

Судя по всему, Вы на него ну очень внимательно смотрели.

2021-05-05 18:11 UTC, alexander-kurdakov commented on src/eighthHomework/QuadTree.fs
> +    static member transitiveClosure (exTree: extendedTree<'t>) (algStruct: AlgebraicStruct<'t>) =
что-то не подумал для чего. Можно и без него.

2021-05-05 19:03 UTC, alexander-kurdakov commented on src/MatrixGenerator/Main.fs
> +            | Sparsity _ -> "Specify the sparsity as number from 0.0 to 1.0"
добавил

2021-05-11 07:28 UTC, gsvgit commented on src/eighthHomework/QuadTree.fs
>      static member sumExTree (x: extendedTree<'t>) (y: extendedTree<'t>) (algStruct: AlgebraicStruct<'t>) =
И всё же. Почему они статики? Если у меня есть один, то я могу его умножить на другой.

2021-05-11 13:10 UTC, alexander-kurdakov commented on src/eighthHomework/QuadTree.fs
>      static member sumExTree (x: extendedTree<'t>) (y: extendedTree<'t>) (algStruct: AlgebraicStruct<'t>) =
Это правда!

2021-05-16 14:02 UTC, gsvgit reviewed
А тесты на генератор есть?

2021-08-20 05:52 UTC, gsvgit requested changes

2021-08-20 05:52 UTC, gsvgit commented on build.fsx
> +let disableCodeCoverage = environVarAsBoolOrDefault "DISABLE_COVERAGE" true
М..... Что, сложно нужное количество тестов написать?

2021-08-20 05:52 UTC, gsvgit commented on src/MatrixGenerator/Generator.fs
> +    let mutable text = ""
1) Есть же String.concat Неужели через него нельзя?
2) Вообще говря, в файл можно писать массив строк. Зачем всё в одну портянку собирать?

2021-08-20 05:52 UTC, gsvgit commented on src/eighthHomework/Output.fs
> +    let originalLst = (exTree.toSparseMatrix |> SparseMatrix.toListOfCells)
А зачем скобки?

2021-08-20 05:52 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +let readIntMatrix path =
Так а что это не тест? Почему только на инты?

2021-08-30 06:31 UTC, gsvgit requested changes
Ещё немного, ещё чуть-чуть

2021-08-30 06:31 UTC, gsvgit commented on src/MatrixGenerator/writePrint.fs
> +    let lst = [for i in 0 .. mtx.GetLength(1) - 1 do
Частично справились. Теперь бы ещё понять, как не хранить все строки в памяти.

2021-08-30 06:31 UTC, gsvgit commented on tests/MatrixGenerator.Tests/GeneratorTests.fs
> +//open Generator
Чой-то. Не работают?

2021-08-30 06:31 UTC, gsvgit commented on tests/MatrixGenerator.Tests/GeneratorTests.fs
> +//open Generator
Что-то я не понял решения просто убрать тесты, в том числе на чтение-генерацию.

2021-08-31 16:24 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/GeneratorTests.fs
> +//open Generator
почему? я их не трогал. Забыл удалить лишний файл

2021-09-02 06:47 UTC, gsvgit requested changes

2021-09-02 06:47 UTC, gsvgit commented on docs/coverage/seventhHomework_MyString.htm
> +<!DOCTYPE html>
А что это за куча файлов вдруг появилась? Они точно должны быть в репозитории?

2021-09-02 06:47 UTC, gsvgit commented on src/MatrixGenerator/writePrint.fs
> +    for i in 0 .. size - 1 do
Костылики, конечно, но уже лучше. Про seq почитайте. С ним должно быть ещё проще.

2021-09-02 06:47 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            let newMatrix =
Если что, это не тест.

2021-09-02 11:08 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            let newMatrix =
почему?

2021-09-02 11:57 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            let newMatrix =
Не поверите, но по поределению. Где и что тут проверяется?

2021-09-03 07:34 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            let newMatrix =
Но эта функция не является тестом. Так? Если вдруг не равно, то что произойдёт?

2021-09-03 09:37 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            let newMatrix =
понял про что Вы.

2021-09-07 07:04 UTC, gsvgit requested changes

2021-09-07 07:04 UTC, gsvgit commented on src/MatrixGenerator/writePrint.fs
> +        Seq.iteri (fun i symb -> writeToFile <| (symb.ToString() + space i)) s
Что за ад?) Можно ещё проще. Почитайте https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealllines?view=net-5.0

2021-09-07 07:04 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
А почему он property?

2021-09-07 10:17 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
Чтобы исключить ситуацию, когда у генератора случайно получилось создать матрицу заявленной разреженности.

2021-09-07 10:24 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
Чего? Не поянл. Смотрите. Вы в тесте даже не используете возможность генерировать входные данные. Почему тогда тест так оформлен?

2021-09-07 19:00 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
а, может быть Вы подумали, что newMatrix это матрица, а не функция.

2021-09-08 04:07 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
Нет. Я просто вижу в 22 строке fun _ ->

2021-09-08 14:46 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
переделал

2021-09-08 20:47 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +            testProperty "sparsity" <| fun _ ->
но я не понял, что в этом проблемного

2021-09-13 08:32 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +                Expect.equal (Math.Round(nons / numOfElems, 1)) (Math.Round(sparsity, 1)) "sparsity does not converge"
А почему здесь такое грубое округление?

2021-09-13 08:35 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +                    match size with
Что?
1. Почему не поиментовать сразу элементы кортежа? Зачем матчить?
2. Зачем там какая-то дикая арифметика внутри?

2021-09-13 08:35 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +    | line, col, sparsity -> GeneratorConfig(Int, line, col, sparsity, 1, __SOURCE_DIRECTORY__)
Зачем матчить тройку?

2021-09-13 08:36 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +let path = __SOURCE_DIRECTORY__ + "/Matrix0.txt"
А если я несколько тестов захочу на генератор?

2021-09-13 10:12 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +let path = __SOURCE_DIRECTORY__ + "/Matrix0.txt"
Что значит несколько? Не понимаю( По очереди в один и тот же файл генерируются матрицы, читаются и проходят тесты. Зачем создавать 100 разных файлов?

2021-09-13 10:14 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +let path = __SOURCE_DIRECTORY__ + "/Matrix0.txt"
За тем, что тесты можно параллельно запускать.

2021-09-13 10:39 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +                    match size with
2. обычно подаются такие значения: (0, 0, 0) А если попросить флоат, то....

2021-09-13 13:01 UTC, alexander-kurdakov commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +                Expect.equal (Math.Round(nons / numOfElems, 1)) (Math.Round(sparsity, 1)) "sparsity does not converge"
с более точным на матрицах небольших размерах генератор не справляется =(

2021-09-13 13:03 UTC, gsvgit commented on tests/MatrixGenerator.Tests/MatrixGeneratorTests.fs
> +                Expect.equal (Math.Round(nons / numOfElems, 1)) (Math.Round(sparsity, 1)) "sparsity does not converge"
Это, простите, как? Может Вы просто не очень правильно что-то вычисляете?

2021-09-24 08:42 UTC, gsvgit approved these changes
Ладно, вымучили.

2021-09-24 16:54 UTC, merged